### ISSUE TITLE
directions for direct download

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/idsserver#1]
please put some directions on the front page about how people should download the executable, if they just go to idsserver it's not clear that for most users they should just  downloadn this; https://github.com/SeedlingsBabylab/idslabel/releases/tag/v0.0.6

(similarly, good to put that workflow from the email somewhere on this page or link to a wiki page that has those directions)

**Comment by andreiamatuni** [comment]
I'll add that info to this page and to the readme in idslabel. Users should generally avoid idsserver altogether, unless they want to host their own idsserver and label their own files locally.
