### ISSUE TITLE
how does save classifications work?

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/idsserver#2]
unclear how "save classifications" works. what's "save" vs. "save as" do? 
Then it's not clear when and how the user should save: I did it at the very end and it just gave me the last block's annotations, should users save after every block to get local copies of the table? 
also: typo in shortcuts, second linux/windows should say save-as.

**Comment by andreiamatuni** [comment]
Save and save as refer to the current block being worked on. So if you press save while working on a block, it'll ask for a path to output file, and then every next time you press save (while working on that block), it'll update the file for that block. Save as tells it you want to save to a different output path. If you want local copies of the classifications, then you should Save+as for each block. I'm going to add some functionality to idsserver to be able to query the classifications that were sent to the server. Also, I just fixed the typo, thank you for noticing it.
